### ISSUE TITLE
フロント（バックからの情報を表示、パドル位置を送信、その他の設計機能）

### ISSUE THREAD

**Issue by kaaaaakun** [kaaaaakun/ft_transcendence#128]
#### 背景
- AsyncAPI完成と同時に開始

#### やりたいこと
- バックエンドと通信して、ボールの位置を表示させつつ、パドルを移動させる。

#### やらないこと
- キーボードの複数キーの同時送信
- [ ] #160
- [ ] リファクタリング (バックエンドとの変数の共通化など)

#### 達成条件・確認項目
- バックからの情報を表示、
- パドル位置を送信

--- 
#### 実装方針 (todo)

通信系
- [x] アクセス時のjsonの変更に対応 
- [x] wsの通信
- [x] wsのクエリ・認証まわりの策定
- [x] ws json送信
- [x] ws json受信

描画系
- [x] ボール・パドルの描画
- [x] キーボード入力の管理
- [x] ゲーム終了の判定・ボタンの出現・リクエスト投げる系

---
確認方法
```
make local
make mock-start
```
これで、一応遊べるはずです！

**Comment by kaaaaakun** [comment]
```
=> ERROR [build 4/4] RUN pnpm build                                                 0.8s
------
 > [build 4/4] RUN pnpm build:
0.598
0.598 > web@0.0.0 build /usr/src/vite
0.598 > vite build
0.598
0.787 /usr/src/vite/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/native.js:59
0.787 		throw new Error(
0.787 		      ^
0.787
0.787 Error: Cannot find module @rollup/rollup-linux-arm64-musl. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
0.787     at requireWithFriendlyError (/usr/src/vite/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/native.js:59:9)
0.787     at Object.<anonymous> (/usr/src/vite/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/native.js:68:76)
0.787     ... 3 lines matching cause stack trace ...
0.787     at Module._load (node:internal/modules/cjs/loader:1024:12)
0.787     at cjsLoader (node:internal/modules/esm/translators:348:17)
0.787     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:297:7)
0.787     at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
0.787     at async ModuleLoader.import (node:internal/modules/esm/loader:316:24) {
0.787   [cause]: Error: Cannot find module '@rollup/rollup-linux-arm64-musl'
0.787   Require stack:
0.787   - /usr/src/vite/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/native.js
0.787       at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
0.787       at Module._load (node:internal/modules/cjs/loader:986:27)
0.787       at Module.require (node:internal/modules/cjs/loader:1233:19)
0.787       at require (node:internal/modules/helpers:179:18)
0.787       at requireWithFriendlyError (/usr/src/vite/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/native.js:41:10)
0.787       at Object.<anonymous> (/usr/src/vite/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/native.js:68:76)
0.787       at Module._compile (node:internal/modules/cjs/loader:1358:14)
0.787       at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
0.787       at Module.load (node:internal/modules/cjs/loader:1208:32)
0.787       at Module._load (node:internal/modules/cjs/loader:1024:12) {
0.787     code: 'MODULE_NOT_FOUND',
0.787     requireStack: [
0.787       '/usr/src/vite/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/native.js'
0.787     ]
0.787   }
0.787 }
0.787
0.787 Node.js v20.14.0
0.794  ELIFECYCLE  Command failed with exit code 1.
------
Dockerfile:30
--------------------
  28 |         pnpm install --frozen-lockfile
  29 |
  30 | >>> RUN pnpm build
  31 |
--------------------
ERROR: failed to solve: process "/bin/sh -c pnpm build" did not complete successfully: exit code: 1
```

**Comment by kaaaaakun** [comment]
```
🌟 22:17 /static-builder 128-ssp-front % pnpm install
Packages: +31
+++++++++++++++++++++++++++++++
Progress: resolved 78, reused 31, downloaded 0, added 31, done

devDependencies:
+ @biomejs/biome 1.8.3 (1.9.4 is available)
+ @popperjs/core 2.11.8
+ bootstrap 5.3.3
+ sass 1.77.6 (1.83.0 is available)
+ vite 5.4.11 (6.0.5 is available)

Done in 4.5s
```

```
 => ERROR [build 4/4] RUN pnpm build                                                                  0.7s
------
 > [build 4/4] RUN pnpm build:
0.532
0.532 > web@0.0.0 build /usr/src/vite
0.532 > vite build
0.532
0.678 /usr/src/vite/node_modules/.pnpm/rollup@4.29.1/node_modules/rollup/dist/native.js:64
0.678 		throw new Error(
0.678 		      ^
0.678
0.678 Error: Cannot find module @rollup/rollup-linux-arm64-musl. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
0.678     at requireWithFriendlyError (/usr/src/vite/node_modules/.pnpm/rollup@4.29.1/node_modules/rollup/dist/native.js:64:9)
0.678     at Object.<anonymous> (/usr/src/vite/node_modules/.pnpm/rollup@4.29.1/node_modules/rollup/dist/native.js:73:76)
0.678     ... 3 lines matching cause stack trace ...
0.678     at Module._load (node:internal/modules/cjs/loader:1024:12)
0.678     at cjsLoader (node:internal/modules/esm/translators:348:17)
0.678     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:297:7)
0.678     at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
0.678     at async ModuleLoader.import (node:internal/modules/esm/loader:316:24) {
0.678   [cause]: Error: Cannot find module '@rollup/rollup-linux-arm64-musl'
0.678   Require stack:
0.678   - /usr/src/vite/node_modules/.pnpm/rollup@4.29.1/node_modules/rollup/dist/native.js
0.678       at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
0.678       at Module._load (node:internal/modules/cjs/loader:986:27)
0.678       at Module.require (node:internal/modules/cjs/loader:1233:19)
0.678       at require (node:internal/modules/helpers:179:18)
0.678       at requireWithFriendlyError (/usr/src/vite/node_modules/.pnpm/rollup@4.29.1/node_modules/rollup/dist/native.js:46:10)
0.678       at Object.<anonymous> (/usr/src/vite/node_modules/.pnpm/rollup@4.29.1/node_modules/rollup/dist/native.js:73:76)
0.678       at Module._compile (node:internal/modules/cjs/loader:1358:14)
0.678       at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
0.678       at Module.load (node:internal/modules/cjs/loader:1208:32)
0.678       at Module._load (node:internal/modules/cjs/loader:1024:12) {
0.678     code: 'MODULE_NOT_FOUND',
0.678     requireStack: [
0.678       '/usr/src/vite/node_modules/.pnpm/rollup@4.29.1/node_modules/rollup/dist/native.js'
0.678     ]
0.678   }
0.678 }
0.678
0.678 Node.js v20.14.0
0.683  ELIFECYCLE  Command failed with exit code 1.
------
Dockerfile:30
--------------------
  28 |         pnpm install --frozen-lockfile
  29 |
  30 | >>> RUN pnpm build
  31 |
--------------------
ERROR: failed to solve: process "/bin/sh -c pnpm build" did not complete successfully: exit code: 1
```
