### ISSUE TITLE
A bad request occurred while creating a new tournament

### ISSUE THREAD

**Issue by jizots** [kaaaaakun/ft_transcendence#67]
トーナメント作成すると、裏でBadRequestになっている。
settings.pyでallowedhostをreverseproxyにしていることが原因で、転送されてくるホストのlocalhostにするのが正しい。

**Comment by jizots** [comment]
export const api = new FetchWrapper(
  import.meta.env.VITE_API_URL ?? 'http://localhost',
)
もよくなさそう。https -> httpリダイレクトしてるからどこかで拒否されてる。
```
Access to fetch at 'http://localhost/api/tournaments/local/' from origin 'https://localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
index-DjLj8yLn.js:1 
        
        
       POST http://localhost/api/tournaments/local/ net::ERR_FAILED
post @ index-DjLj8yLn.js:1
qe @ index-DjLj8yLn.js:1
Ye @ index-DjLj8yLn.js:1
index-DjLj8yLn.js:1 Error: TypeError: Failed to fetch
    at Ue.post (index-DjLj8yLn.js:1:6443)
    at Object.qe [as createLocalTournament] (index-DjLj8yLn.js:1:7058)
    at HTMLFormElement.Ye (index-DjLj8yLn.js:1:8297)
```
